### ISSUE TITLE
(S) profile-search-page-resizing

### ISSUE THREAD

**Issue by emluo555** [Hack4Impact-Princeton/alp-portal#371]
<img width="752" alt="Screenshot 2024-04-05 at 6 08 35 PM" src="https://github.com/Hack4Impact-Princeton/alp-portal/assets/73714192/5fd914a3-6d71-4924-adaa-7f41663b765c">
- fixing the spacing issue of the search bar when the screen size shrinks (move the search bar under)

**Comment by crimmzx** [comment]
media query king!

**Comment by emluo555** [comment]
> media query king!

no literally facts
