### ISSUE TITLE
(S) profile-search-cards-aesthetics

### ISSUE THREAD

**Issue by emluo555** [Hack4Impact-Princeton/alp-portal#372]
<img width="1041" alt="Screenshot 2024-04-05 at 6 12 51 PM" src="https://github.com/Hack4Impact-Princeton/alp-portal/assets/73714192/41c706d8-4ae1-4ccd-b2b9-8d0e7147de54">
- making the colors of the buttons 'friend, unfriend, request' match the colors on figma. also moving the button so that its to the right of the profile picture, and aligned with the bottom of it (ignore the badges part)
<img width="866" alt="Screenshot 2024-04-05 at 6 16 03 PM" src="https://github.com/Hack4Impact-Princeton/alp-portal/assets/73714192/e8ccf50d-d4b4-4c35-aa50-af49aeefa5fd">

**Comment by crimmzx** [comment]
is the button under the profile picture?

**Comment by emluo555** [comment]
<img width="439" alt="Screenshot 2024-04-11 at 7 36 10 PM" src="https://github.com/Hack4Impact-Princeton/alp-portal/assets/73714192/59f5564f-bcd9-4e11-88a8-f902e5df233b">
